#!/usr/bin/env bash
#
# generate-test-coverage-table.sh
#
# Regenerates the "Existing test coverage, by package" table in
# docs/TEST_COVERAGE.md from the actual current state of internal/ -
# package names and test-function counts only, both objectively
# derivable facts. Descriptions of what each package DOES are not
# generated here (a script can't infer that reliably) - the table instead
# points to docs/ARCHITECTURE.md, which covers package responsibilities
# with real, verified descriptions already.
#
# This exists because the table it replaces was hand-maintained and
# already proved fragile once: a manual scan at `internal/` depth 1
# missed internal/adapters/iso20022 (nested one level deeper) and
# cmd/live-catalog-sync, both pre-existing tested packages. This script
# walks the real directory tree recursively, so that specific mistake
# can't recur.
#
# Usage:
#   ./generate-test-coverage-table.sh              regenerate in place
#   ./generate-test-coverage-table.sh --check       exit 1 if docs/TEST_COVERAGE.md
#                                                    is stale relative to the
#                                                    current repo (suitable for CI)
#   ./generate-test-coverage-table.sh --print       print the table to stdout only
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

DOC_PATH="docs/TEST_COVERAGE.md"
BEGIN_MARKER="<!-- BEGIN GENERATED TEST COVERAGE TABLE -->"
END_MARKER="<!-- END GENERATED TEST COVERAGE TABLE -->"

MODE="${1:-apply}"

generate_table() {
  echo "$BEGIN_MARKER"
  echo "<!-- Generated by scripts/docs/generate-test-coverage-table.sh - do not hand-edit between these markers. -->"
  echo "| Package | Tests | Notes |"
  echo "|---|---|---|"

  total_tests=0
  total_packages=0
  zero_test_packages=()

  # Recursive, unlike the original hand-maintained table's depth-1 scan -
  # this is the specific fix for the exact mistake that made this script
  # necessary in the first place.
  while IFS= read -r -d '' dir; do
    # Only real Go packages: directories that actually contain a .go file.
    if ! compgen -G "$dir/*.go" > /dev/null 2>&1; then
      continue
    fi
    pkg="${dir#internal/}"
    # grep exits nonzero both when it finds zero matches AND when the glob
    # matches no files at all (e.g. a package with no *_test.go files at
    # all, like internal/platformapi as of this writing) - under
    # `set -e` + `pipefail`, either case silently kills this whole script
    # mid-loop with no error message, which is exactly what happened while
    # writing this script: it silently stopped partway through the
    # alphabet the first time it hit a package with zero matching test
    # functions, and produced a shorter, WRONG table that still looked
    # plausible. The `|| true` here is load-bearing, not cosmetic.
    test_count=$({ grep -h "^func Test" "$dir"/*_test.go 2>/dev/null || true; } | wc -l | tr -d ' ')
    total_packages=$((total_packages + 1))
    total_tests=$((total_tests + test_count))

    notes=""
    if [ "$test_count" = "0" ]; then
      notes="**zero test coverage**"
      zero_test_packages+=("$pkg")
    fi

    echo "| \`$pkg\` | $test_count | $notes |"
  done < <(find internal -type d -print0 | sort -z)

  echo ""
  echo "**Totals (generated, not hand-counted): $total_tests test functions across $total_packages \`internal/\` packages.**"
  if [ "${#zero_test_packages[@]}" -gt 0 ]; then
    echo ""
    old_ifs="$IFS"
    IFS=,
    joined="${zero_test_packages[*]}"
    IFS="$old_ifs"
    echo "Zero test coverage: ${joined//,/, }."
  fi
  echo ""
  echo "See docs/ARCHITECTURE.md for what each package actually does - this table only tracks test presence and count, which a script can verify; package responsibility descriptions require human judgment and live there instead, so they don't silently drift out of sync with a hand-maintained copy here."
  echo "$END_MARKER"
}

case "$MODE" in
  --print)
    generate_table
    ;;
  --check)
    if [ ! -f "$DOC_PATH" ]; then
      echo "FAIL: $DOC_PATH does not exist" >&2
      exit 1
    fi
    fresh="$(generate_table)"
    current="$(awk "/^${BEGIN_MARKER//\//\\/}\$/,/^${END_MARKER//\//\\/}\$/" "$DOC_PATH")"
    if [ "$fresh" != "$current" ]; then
      echo "FAIL: $DOC_PATH's generated table is stale. Run this script without --check to regenerate it." >&2
      diff <(echo "$current") <(echo "$fresh") || true
      exit 1
    fi
    echo "OK: $DOC_PATH's generated table is up to date."
    ;;
  apply)
    [ -f "$DOC_PATH" ] || { echo "$DOC_PATH not found" >&2; exit 1; }
    fresh="$(generate_table)"
    python3 -c "
import sys
begin = '''$BEGIN_MARKER'''
end = '''$END_MARKER'''
with open('$DOC_PATH') as f:
    content = f.read()
if begin not in content or end not in content:
    print('ERROR: markers not found in $DOC_PATH - add them once by hand around the table to regenerate, then re-run.', file=sys.stderr)
    sys.exit(1)
before = content.split(begin)[0]
after = content.split(end)[1]
new_content = before + '''$fresh'''.replace('$BEGIN_MARKER', begin, 1).replace('$END_MARKER', end, 1) + after
with open('$DOC_PATH', 'w') as f:
    f.write(new_content)
print('Updated $DOC_PATH')
"
    ;;
  *)
    echo "Usage: $0 [--check|--print]" >&2
    exit 2
    ;;
esac
