// See cmd/platform-api/main_test.go for the black-box subprocess pattern.
// This is the capstone of the review pipeline: false-positive
// classification, policy engine, RAG retrieval, and analyst-note
// generation, all orchestrated together. Every flag default already
// points at a real committed config (baseline-r1.json,
// countervailing-evidence-r1.json, transaction-screening-r1.yaml,
// test/golden/rag/corpus-snapshot.json, retrieval-policy-r1.json,
// configs/models/granite-analyst-note-r1.json), and --note-provider
// "fixture" avoids needing a live Ollama instance. The one required
// input - a matcherprovider.ResultBatch - is generated by actually
// running cmd/matcher-run against its own known-working fixture (see
// docs/TEST_DATA.md's quickstart), not hand-authored: this is the same
// "candidate-result-batch/v1alpha1" schema matcher-run already produces.
package main_test

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"testing"
)

var (
	binaryPath        string
	matcherResultPath string
)

func TestMain(m *testing.M) {
	dir, err := os.MkdirTemp("", "review-run-test-*")
	if err != nil {
		panic(err)
	}
	defer os.RemoveAll(dir)

	binaryPath = filepath.Join(dir, "review-run")
	build := exec.Command("go", "build", "-o", binaryPath, ".")
	if out, err := build.CombinedOutput(); err != nil {
		panic("failed to build cmd/review-run for testing: " + err.Error() + "\n" + string(out))
	}

	matcherRunBin := filepath.Join(dir, "matcher-run")
	build = exec.Command("go", "build", "-o", matcherRunBin, "../matcher-run")
	if out, err := build.CombinedOutput(); err != nil {
		panic("failed to build cmd/matcher-run (prerequisite) for testing: " + err.Error() + "\n" + string(out))
	}

	repoRoot, err := filepath.Abs("../..")
	if err != nil {
		panic(err)
	}
	mrCmd := exec.Command(matcherRunBin,
		"-provider", "ofac-baseline",
		"-catalog", "test/golden/ofac/ofac-sdn-fixture.runtime.owpcat",
		"-matcher-profiles", "configs/matcher-profiles/ofac-name-baseline-r1.json",
		"-input", "requests", "-output", "results",
		"test/golden/iso20022/pacs008/pacs008-basic.matcher-requests.json")
	mrCmd.Dir = repoRoot
	matcherResults, err := mrCmd.Output()
	if err != nil {
		panic("failed to generate prerequisite matcher results via matcher-run: " + err.Error())
	}
	matcherResultPath = filepath.Join(dir, "matcher-results.json")
	if err := os.WriteFile(matcherResultPath, matcherResults, 0o644); err != nil {
		panic(err)
	}

	os.Exit(m.Run())
}

func run(args ...string) (stdout, stderr string, exitCode int) {
	cmd := exec.Command(binaryPath, args...)
	cmd.Dir = "../.." // repo root, so the many default config flag values resolve
	var outBuf, errBuf bytes.Buffer
	cmd.Stdout = &outBuf
	cmd.Stderr = &errBuf
	err := cmd.Run()
	if err == nil {
		return outBuf.String(), errBuf.String(), 0
	}
	if exitErr, ok := err.(*exec.ExitError); ok {
		return outBuf.String(), errBuf.String(), exitErr.ExitCode()
	}
	panic("review-run did not run at all (not just a nonzero exit): " + err.Error())
}

func TestHappyPath_FullPipelineWithDefaults(t *testing.T) {
	stdout, stderr, code := run(matcherResultPath)
	if code != 0 {
		t.Fatalf("expected exit code 0, got %d (stderr: %q)", code, stderr)
	}
	if !bytes.Contains([]byte(stdout), []byte(`"schema_version": "review-run-bundle/v1alpha1"`)) {
		t.Fatalf("expected a review-run-bundle result, got: %s", stdout)
	}
	if !bytes.Contains([]byte(stdout), []byte(`"input_result_batch"`)) {
		t.Fatalf("expected the bundle to embed the input result batch, got: %s", stdout)
	}
}

func TestNoArgsFailsWithUsageMessage(t *testing.T) {
	_, stderr, code := run()
	if code != 1 {
		t.Fatalf("expected exit code 1 with no args, got %d (stderr: %q)", code, stderr)
	}
	if !bytes.Contains([]byte(stderr), []byte("usage: review-run")) {
		t.Fatalf("expected usage message on stderr, got %q", stderr)
	}
}

func TestMissingInputFileFailsCleanly(t *testing.T) {
	_, stderr, code := run("/definitely/does/not/exist.json")
	if code != 1 {
		t.Fatalf("expected exit code 1 for a missing input file, got %d (stderr: %q)", code, stderr)
	}
	if bytes.Contains([]byte(stderr), []byte("panic:")) {
		t.Fatalf("got a panic instead of a clean error for a missing input file: %s", stderr)
	}
}

func TestUnsupportedNoteProviderFailsCleanly(t *testing.T) {
	_, stderr, code := run("-note-provider", "bogus-provider", matcherResultPath)
	if code != 1 {
		t.Fatalf("expected exit code 1 for an unsupported --note-provider, got %d (stderr: %q)", code, stderr)
	}
	if !bytes.Contains([]byte(stderr), []byte("unsupported --note-provider")) {
		t.Fatalf("expected an 'unsupported --note-provider' message, got %q", stderr)
	}
}

func TestNoteProviderDisabledSkipsNoteGeneration(t *testing.T) {
	stdout, stderr, code := run("-note-provider", "disabled", matcherResultPath)
	if code != 0 {
		t.Fatalf("expected exit code 0 with --note-provider disabled, got %d (stderr: %q)", code, stderr)
	}
	if !bytes.Contains([]byte(stdout), []byte(`"schema_version": "review-run-bundle/v1alpha1"`)) {
		t.Fatalf("expected a review-run-bundle result even with notes disabled, got: %s", stdout)
	}
}
